Marfrig.MRCG.Web/Controllers/CompraGadoController.cs
using AutoMapper;
using Marfrig.MRCG.Domain.Contracts.AppServices;
using Marfrig.MRCG.Domain.Models;
using Marfrig.MRCG.Domain.ViewModels;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace Marfrig.MRCG.Web.Controllers
{
    public class CompraGadoController : Controller
    {
        private readonly ICompraGadoAppService _compraGadoAppService;
        private readonly IPecuaristaAppService _pecuaristaAppService;

        public CompraGadoController(ICompraGadoAppService compraGadoAppService, IPecuaristaAppService pecuaristaAppService)
        {
            _compraGadoAppService = compraGadoAppService;
            _pecuaristaAppService = pecuaristaAppService;
        }

        public ActionResult Index()
        {
            ViewBag.Pecuaristas = new SelectList(_pecuaristaAppService.GetAll(), "PecuaristaId", "Nome", "Selecione");
            var listaComprasGado = Mapper.Map<IEnumerable<CompraGado>, IEnumerable<CompraGadoViewModel>>(_compraGadoAppService.GetAllComplete());

            return View(listaComprasGado);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompraGadoViewModel compraGado = Mapper.Map<CompraGado, CompraGadoViewModel>(_compraGadoAppService.GetById((int)id));
            if (compraGado == null)
            {
                return HttpNotFound();
            }

            return View(compraGado);
        }

        public ActionResult Create()
        {
            var pecuaristas = _pecuaristaAppService.GetAll();
            ViewBag.PecuaristaId = new SelectList(pecuaristas, "PecuaristaId", "Nome");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompraGadoViewModel compraGadoViewModel)
        {
            if (ModelState.IsValid)
            {
                _compraGadoAppService.Create(Mapper.Map<CompraGadoViewModel, CompraGado>(compraGadoViewModel));
                return RedirectToAction("Index");
            }
            var pecuaristas = _pecuaristaAppService.GetAll();
            ViewBag.PecuaristaId = new SelectList(pecuaristas, "PecuaristaId", "Nome", compraGadoViewModel.PecuaristaId);

            return View(compraGadoViewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompraGadoViewModel compraGadoViewModel = Mapper.Map<CompraGado, CompraGadoViewModel>(_compraGadoAppService.GetById((int)id));
            if (compraGadoViewModel == null)
            {
                return HttpNotFound();
            }
            var pecuaristas = _pecuaristaAppService.GetAll();
            ViewBag.PecuaristaId = new SelectList(pecuaristas, "PecuaristaId", "Nome", compraGadoViewModel.PecuaristaId);
            return View(compraGadoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CompraGadoViewModel compraGadoViewModel)
        {
            if (ModelState.IsValid)
            {
                CompraGado compraGado = _compraGadoAppService.GetById(compraGadoViewModel.CompraGadoId);
                compraGado.PecuaristaId = compraGadoViewModel.PecuaristaId;
                compraGado.DataEntrega = compraGadoViewModel.DataEntrega;
                _compraGadoAppService.Update(compraGado);
                return RedirectToAction("Index");
            }
            var pecuaristas = _pecuaristaAppService.GetAll();
            ViewBag.PecuaristaId = new SelectList(pecuaristas, "PecuaristaId", "Nome", compraGadoViewModel.PecuaristaId);
            return View(compraGadoViewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompraGadoViewModel compraGadoViewModel = Mapper.Map<CompraGado, CompraGadoViewModel>(_compraGadoAppService.GetById((int)id));
            if (compraGadoViewModel == null)
            {
                return HttpNotFound();
            }
            return View(compraGadoViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompraGado compraGado = _compraGadoAppService.GetById((int)id);
            _compraGadoAppService.Remove(compraGado);
            return RedirectToAction("Index");
        }
    }
}

Marfrig.MRCG.Web/Views/CompraGado/Create.cshtml
@model Marfrig.MRCG.Domain.ViewModels.CompraGadoViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compra de Gado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DataEntrega, "Data de Entrega", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataEntrega, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                @Html.ValidationMessageFor(model => model.DataEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PecuaristaId, "Pecuarista", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PecuaristaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PecuaristaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Marfrig.MRCG.Web/Views/CompraGado/Delete.cshtml
@model Marfrig.MRCG.Domain.ViewModels.CompraGadoViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Tem certeza que gostaria de apagar esse registro?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pecuarista.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pecuarista.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataEntrega)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEntrega)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Marfrig.MRCG.Web/Views/CompraGado/Details.cshtml
@model Marfrig.MRCG.Domain.ViewModels.CompraGadoViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>Compra de Gado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pecuarista.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pecuarista.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataEntrega)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEntrega)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.CompraGadoId }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Marfrig.MRCG.Web/Views/CompraGado/Edit.cshtml
@model Marfrig.MRCG.Domain.ViewModels.CompraGadoViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compra de Gado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompraGadoId)

        <div class="form-group">
            @Html.LabelFor(model => model.DataEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataEntrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PecuaristaId, "PecuaristaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PecuaristaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PecuaristaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Marfrig.MRCG.Web/Views/CompraGado/Index.cshtml
@using MVCGrid.Web
@model IEnumerable<Marfrig.MRCG.Domain.ViewModels.CompraGadoViewModel>

@{
    ViewBag.Title = "Consulta de compra de gado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/MVCGridHandler.axd/script.js"></script>

<div class="row">
    <div class="col-md-1">
        <input type="submit" value="Pesquisar" class="btn btn-secondary">
    </div>
    <div class="col-md-1">
        <input type="submit" value="Imprimir" class="btn btn-secondary">
    </div>
    <div class="col-md-1">
        <input type="submit" value="Adicionar" class="btn btn-secondary" onclick="location.href='@Url.Action("Create", "CompraGado")'">
    </div>
    <div class="col-md-1">
        <input type="submit" value="Alterar" class="btn btn-secondary">
    </div>
    <div class="col-md-1">
        <input type="submit" value="Excluir" class="btn btn-secondary" onclick="location.href='@Url.Action("Delete", "CompraGado")'">
    </div>
</div>

<br />
<br />

<div class="row">
    <div class="col-md-2 text-right">
        Id:
    </div>
    <div class="col-md-2 text-left">
        @Html.TextBox("Id", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="col-md-1 text-right">
        Pecuarista:
    </div>
    <div class="col-md-2 text-left">
        @Html.DropDownList("Pecuaristas", null, htmlAttributes: new { @class = "form-control" })
    </div>
</div>

<br />

<div class="row">
    <div class="col-md-2 text-right">
        Data de Entrega de:
    </div>
    <div class="col-md-2 text-left">
        @Html.TextBox("DataEntrega", null, htmlAttributes: new { @class = "form-control", @type = "date" })
    </div>
    <div class="col-md-1 text-right">
        Até:
    </div>
    <div class="col-md-2 text-left">
        @Html.TextBox("DataAte", null, htmlAttributes: new { @class = "form-control", @type = "date" })
    </div>
</div>

<br />
<br />

<div class="row">
    <div class="col-md-12">
        @Html.MVCGrid("CompraGadoGrid")
    </div>
</div>